# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install remotes package
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install dependencies
        run: remotes::install_github("richelbilderbeek/bianchietal2017")
        shell: Rscript {0}

      - name: get UP000005640_9606.fasta.gz
        run: make UP000005640_9606.fasta.gz

      - name: get UP000005640_9606.fasta
        run: make UP000005640_9606.fasta

      - name: simplify FASTA to 2 proteins
        run: ./simplify_fasta.sh

      - name: make
        run: make

      - name: show results
        run: cat results.csv

