# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install remotes package
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install R.utils
        run: install.packages(c("R.utils", "readxl"))
        shell: Rscript {0}

      - name: Install dependencies
        run: remotes::install_github("richelbilderbeek/bianchi_et_al_2017")
        shell: Rscript {0}

      - name: Install mhcnpreds
        run: remotes::install_github("jtextor/epitope-prediction")
        shell: Rscript {0}

      - name: Install mhcnpreds
        run: remotes::install_github("richelbilderbeek/epiprepreds")
        shell: Rscript {0}

      - name: Install bbbq
        run: remotes::install_github("richelbilderbeek/bbbq")
        shell: Rscript {0}

      - name: Install pureseqtmr
        run: remotes::install_github("richelbilderbeek/pureseqtmr")
        shell: Rscript {0}

      - name: Install tmhmm
        run: remotes::install_github("richelbilderbeek/tmhmm")
        shell: Rscript {0}

      - name: make
        run: make

      - name: show results
        run: cat tmhs_pureseqtm.csv

