on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "R.utils", "readxl"))
          remotes::install_github("richelbilderbeek/bianchi_et_al_2017")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("jtextor/epitope-prediction")
          remotes::install_github("richelbilderbeek/epiprepreds")
          remotes::install_github("richelbilderbeek/nmhc2ppreds")
          remotes::install_github("richelbilderbeek/mhcnpreds")
          remotes::install_github("richelbilderbeek/iedbr")
          remotes::install_bioc("Biostrings")
          remotes::install_bioc("msa")
          remotes::install_github("richelbilderbeek/bbbq")
          remotes::install_github("richelbilderbeek/pureseqtmr")
          remotes::install_github("richelbilderbeek/tmhmm")
        shell: Rscript {0}

      - name: make
        run: make matches_1.csv

